// This file will be auto-generated by Convex

import type { ApiFromModules } from "convex/api";
import type * as memories from "../memories";
import type * as patterns from "../patterns";
import type * as cognitiveState from "../cognitiveState";

export type API = ApiFromModules<{
  memories: typeof memories;
  patterns: typeof patterns;
  cognitiveState: typeof cognitiveState;
}>;